services:
  todo:
    container_name: "react_sm"
    image: "frontend_todo"
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5052:3000"
    volumes:
      - .:/app
      - /app/node_modules









